# This workflow will:
#
#   * install Python dependencies
#   * lint & type check with a single version of Python
#   * run automated tests under a virtual framebuffer
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push-Checks

on:
  push:
    # We'll catch issues on `develop` or any PR branch.
    branches-ignore:
      - 'main'
      - 'stable'
      - 'releases'
      - 'beta'

jobs:
  push_checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        cache: 'pip' # caching pip dependencies
        python-version-file: '.python-version'

    - name: Install dependencies
      run: |
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install -e .[legacy-dev,dev]

    - name: Lint and Format with Ruff
      run: |
        ruff check --format=github .
        ruff format --check .

    - name: mypy type checks
      run: |
        ./scripts/mypy-all.sh --platform win32

    - name: translation checks
      run: |
        python ./scripts/find_localised_strings.py --compare-lang L10n/en.template --directory . --ignore coriolis-data

    - name: PyTest tests
      run: |
        xvfb-run pytest
